### ISSUE TITLE
[Bug] Following the instructions does not result in a working setup

### ISSUE THREAD

**Issue by remyhonig** [temporalio/samples-php#17]
### What are you really trying to do?

I want to see Temporal in action with the PHP SDK

### Describe the bug

`docker-compose up` fails with this message:

```
temporal                | Waiting for Temporal server to start...
temporal                | 2022/03/11 23:08:50 Loading config; env=docker,zone=,configDir=config
temporal                | 2022/03/11 23:08:50 Loading config files=[config/docker.yaml]
temporal                | {"level":"info","ts":"2022-03-11T23:08:50.439Z","msg":"Build info","timestamp":"2022-01-10T22:38:35.000Z","git-revision":"b535b87fb","platform":"amd64","go-version":"go1.17.3","server-version":"1.14.2","logging-call-at":"main.go:135"}
temporal                | Unable to create dynamic config client. Error: unable to validate dynamic config: dynamic config: config/dynamicconfig/development.yaml: stat config/dynamicconfig/development.yaml: no such file or directory
temporal exited with code 1
```

### Minimal Reproduction

`docker-compose up`

### Environment/Versions

Docker version 20.10.7, build 20.10.7-0ubuntu5~20.04.2

### Additional context

I only cloned the repo and ran `docker-compose up`

**Comment by yactouatfuture** [comment]
hey 👋 , having the same issue it seems that the `dynamicconfig` folder does not exist in this repo

**Comment by Jared0430** [comment]
Same issue here. After copying the `dynamicconfig` folder from https://github.com/temporalio/docker-compose it appears to work at first, but the app container crashes after a few seconds with 

```
container/init.go:77	error calling internal_init	{"id": "config.Plugin", "error": "config_plugin_init: incompatible versions passed: from: 2.6.0, to: 2.8.3"}
```

**Comment by yactouatfuture** [comment]
@Jared0430 check out your `rr.yaml` and try adding a "version": "2.8.3" at the top of it; found out that without specifying the version, rr was fallbacking to another version

**Comment by sw-yx** [comment]
swyx from Temporal here - sorry about this, will get the maintainers' attention @seregazhuk

**Comment by remyhonig** [comment]
No worries, I got it working, but I wish this project to gain adoption in the PHP space and this might be an unnecessary hurdle. Thanks you for picking it up.
