### ISSUE TITLE
[Feature Request] Upgrade to php 8.1 or 8.2

### ISSUE THREAD

**Issue by ruscon** [temporalio/samples-php#28]
### Is your feature request related to a problem? Please describe.

I tried to install docker with PHP 8.1, but warnings are issued from the PHP side. And because of this, the `app` container falls.

**Comment by astralo** [comment]
we can fix it temporarily if change composer.json file with downgrade temporal sdk version "temporal/sdk": "^2.5",
it'll be enough for building and  starting your containers

**Comment by roxblnfk** [comment]
The issue now seems to be outdated.
